version: "3.0"
services:

  container-bot:
    image: rasa/rasa:3.0.4-full
    container_name: rasa
    networks: 
      - production
    depends_on:
      - container-server-bot
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    public: true
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --credentials
      - credentials.yml
      - --debug
      
  container-server-bot:
    build:
      context: .
      dockerfile: actions.Dockerfile
    image: rasa-actions-server
    container_name: ractions
    networks: 
      - rasa-network
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions

  mongodb:
    image: mongo
    container_name: db
    networks: 
      - rasa-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sprint4

  web:
    build:
      context: Web/
      dockerfile: web.Dockerfile
    image: webchat
    container_name: webchat-app
    depends_on:
      - container-bot
      - container-server-bot
    networks: 
      - production
    ports: 
      - 8080:8080

networks: 
    production:
      driver: bridge